//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPdesk._01_EntiryModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public incident()
        {
            this.incident1 = new HashSet<incident>();
            this.incident11 = new HashSet<incident>();
        }
        /// <summary>
        /// Anamwmmeefafefefe
        /// </summary>
        [Description("Hell if I know")]
        public Nullable<System.Guid> aanmelderafdelingid { get; set; }
        public Nullable<System.Guid> aanmelderbudgethouderid { get; set; }
        public Nullable<System.Guid> aanmelderlokatieid { get; set; }
        public string aanmeldertelefoon { get; set; }
        public Nullable<System.Guid> aanmeldervestigingid { get; set; }
        public string actie { get; set; }
        public Nullable<System.Guid> actiedoorid { get; set; }
        public bool afgemeld { get; set; }
        public Nullable<System.Guid> afhandelingstatusid { get; set; }
        public Nullable<System.Guid> archiefredenid { get; set; }
        public bool bewaakt { get; set; }
        public Nullable<System.Guid> configuratieid { get; set; }
        public Nullable<System.Guid> configuratieobjectid { get; set; }
        public int deelactievolgnummer { get; set; }
        public Nullable<System.Guid> deescalatieredenid { get; set; }
        public bool dnogebruikt { get; set; }
        public Nullable<System.Guid> dnoid { get; set; }
        public Nullable<System.Guid> doorlooptijdid { get; set; }
        public int emailstatus { get; set; }
        public Nullable<System.Guid> escalatieredenid { get; set; }
        public bool gedeescaleerd { get; set; }
        public bool geescaleerd { get; set; }
        public bool gereed { get; set; }
        public Nullable<System.Guid> impactid { get; set; }
        public Nullable<System.Guid> incident_domeinid { get; set; }
        public Nullable<System.Guid> incident_specid { get; set; }
        public Nullable<System.Guid> incidentid { get; set; }
        public Nullable<System.Guid> lijn1actiedoorid { get; set; }
        public Nullable<System.Guid> oplosmethodeid { get; set; }
        public Nullable<System.Guid> persoonid { get; set; }
        public string ref_configuratie { get; set; }
        public Nullable<System.Guid> ref_dnocontractid { get; set; }
        public Nullable<System.Guid> ref_dnodienstid { get; set; }
        public string ref_domein { get; set; }
        public string ref_persnr { get; set; }
        public string ref_specificatie { get; set; }
        public string ref_vestiging { get; set; }
        public Nullable<System.Guid> soortbinnenkomstid { get; set; }
        public Nullable<System.Guid> soortmeldingid { get; set; }
        public int status { get; set; }
        public Nullable<System.Guid> uidaanmk { get; set; }
        public Nullable<System.Guid> uidwijzig { get; set; }
        public System.Guid unid { get; set; }
        public string verzoek { get; set; }
        public int volgnummer { get; set; }
        public double vrijegetal1 { get; set; }
        public double vrijegetal2 { get; set; }
        public bool vrijelogisch1 { get; set; }
        public bool vrijelogisch2 { get; set; }
        public bool vrijelogisch3 { get; set; }
        public bool vrijelogisch4 { get; set; }
        public bool vrijelogisch5 { get; set; }
        public string vrijememo1 { get; set; }
        public string vrijememo2 { get; set; }
        public Nullable<System.Guid> vrijeopzoek1 { get; set; }
        public Nullable<System.Guid> vrijeopzoek2 { get; set; }
        public Nullable<System.Guid> vrijeopzoek3 { get; set; }
        public string ref_debnummer { get; set; }
        public Nullable<System.DateTime> dataanmk { get; set; }
        public Nullable<System.DateTime> datumaangemeld { get; set; }
        public Nullable<System.DateTime> datumafgemeld { get; set; }
        public Nullable<System.DateTime> datumafspraak { get; set; }
        public Nullable<System.DateTime> datumgereed { get; set; }
        public Nullable<System.DateTime> datwijzig { get; set; }
        public Nullable<System.DateTime> vrijedatum1 { get; set; }
        public Nullable<System.DateTime> vrijedatum2 { get; set; }
        public long lijn1tijdbesteed { get; set; }
        public decimal onkosten { get; set; }
        public long tijdbesteed { get; set; }
        public decimal totaleonkosten { get; set; }
        public long totaletijd { get; set; }
        public long verwtijdbesteed { get; set; }
        public long minutendoorlooptijd { get; set; }
        public Nullable<System.Guid> extraaid { get; set; }
        public Nullable<System.Guid> extrabid { get; set; }
        public int dnostatus { get; set; }
        public string korteomschrijving { get; set; }
        public Nullable<System.DateTime> datumafspraaksla { get; set; }
        public Nullable<System.Guid> oplossingid { get; set; }
        public Nullable<System.Guid> locatieid { get; set; }
        public Nullable<System.Guid> vestigingid { get; set; }
        public int betreftkeuze { get; set; }
        public Nullable<System.Guid> operatorid { get; set; }
        public string naam { get; set; }
        public Nullable<System.Guid> extraapersoonid { get; set; }
        public Nullable<System.Guid> extrabpersoonid { get; set; }
        public bool ismajorincident { get; set; }
        public Nullable<System.Guid> majorincidentid { get; set; }
        public Nullable<System.DateTime> vrijedatum3 { get; set; }
        public double vrijegetal3 { get; set; }
        public string vrijememo3 { get; set; }
        public Nullable<System.DateTime> vrijedatum4 { get; set; }
        public double vrijegetal4 { get; set; }
        public string vrijememo4 { get; set; }
        public Nullable<System.DateTime> vrijedatum5 { get; set; }
        public double vrijegetal5 { get; set; }
        public string vrijememo5 { get; set; }
        public Nullable<System.Guid> vrijeopzoek4 { get; set; }
        public Nullable<System.Guid> vrijeopzoek5 { get; set; }
        public string vrijetekst1 { get; set; }
        public string vrijetekst2 { get; set; }
        public string vrijetekst3 { get; set; }
        public string vrijetekst4 { get; set; }
        public string vrijetekst5 { get; set; }
        public Nullable<System.DateTime> attvrijedatum1 { get; set; }
        public double attvrijegetal1 { get; set; }
        public bool attvrijelogisch1 { get; set; }
        public string attvrijememo1 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek1 { get; set; }
        public string attvrijetekst1 { get; set; }
        public Nullable<System.DateTime> attvrijedatum2 { get; set; }
        public double attvrijegetal2 { get; set; }
        public bool attvrijelogisch2 { get; set; }
        public string attvrijememo2 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek2 { get; set; }
        public string attvrijetekst2 { get; set; }
        public Nullable<System.DateTime> attvrijedatum3 { get; set; }
        public double attvrijegetal3 { get; set; }
        public bool attvrijelogisch3 { get; set; }
        public string attvrijememo3 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek3 { get; set; }
        public string attvrijetekst3 { get; set; }
        public Nullable<System.DateTime> attvrijedatum4 { get; set; }
        public double attvrijegetal4 { get; set; }
        public bool attvrijelogisch4 { get; set; }
        public string attvrijememo4 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek4 { get; set; }
        public string attvrijetekst4 { get; set; }
        public Nullable<System.DateTime> attvrijedatum5 { get; set; }
        public double attvrijegetal5 { get; set; }
        public bool attvrijelogisch5 { get; set; }
        public string attvrijememo5 { get; set; }
        public Nullable<System.Guid> attvrijeopzoek5 { get; set; }
        public string attvrijetekst5 { get; set; }
        public System.Guid servicewindowid { get; set; }
        public decimal kosten_artikelen { get; set; }
        public decimal kosten_objecten { get; set; }
        public string externnummer { get; set; }
        public string aanmelderemail { get; set; }
        public string ref_object { get; set; }
        public bool onhold { get; set; }
        public long onholdduration { get; set; }
        public Nullable<System.Guid> operatorgroupid { get; set; }
        public Nullable<System.Guid> escalationoperatorid { get; set; }
        public Nullable<System.DateTime> onholddatum { get; set; }
        public Nullable<System.Guid> urgencyid { get; set; }
        public Nullable<System.Guid> priorityid { get; set; }
        public string bespokememo { get; set; }
        public int importtype { get; set; }
        public Nullable<System.Guid> supplierid { get; set; }
        public string importid { get; set; }
        public Nullable<System.DateTime> importdate { get; set; }
        public bool savedinsecure { get; set; }
        public int ref_main_incident_status { get; set; }
        public string ref_main_incident_bf { get; set; }
        public string ref_main_incident_name { get; set; }
        public Nullable<System.Guid> appointmentid { get; set; }
        public string aanmeldernaam { get; set; }
        public string ref_escalationoperator { get; set; }
        public string ref_operatordynanaam { get; set; }
        public string ref_operatorgroup { get; set; }
        public long resolvedduration { get; set; }
        public long adjusteddurationonhold { get; set; }
        public long adjusteddurationresolved { get; set; }
        public string ref_impact { get; set; }
        public string ref_soortmelding { get; set; }
        public string ref_status { get; set; }
        public Nullable<System.Guid> ref_servicelevelid { get; set; }
        public Nullable<System.Guid> supplierserviceid { get; set; }
        public string ref_progresstrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident> incident1 { get; set; }
        public virtual incident incident2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident> incident11 { get; set; }
        public virtual incident incident3 { get; set; }
    }
}
